### ISSUE TITLE
Rotation doesn't work?

### ISSUE THREAD

**Issue by Demosthenexx** [jlahd/clods-export#1]
Comparing against a simple ODS document made in Libreoffice, they are putting style:text-rotation-angle in the table-cell-properties element. CLODS is putting the angle parameter on style:text-properties. As a result, rotation isn't working.

**Comment by jlahd** [comment]
Thanks for the report! I have now added the `:rotation-angle` keyword argument to `clods:cell-style`. According to the specs, `style:text-properties` also has `text-rotation-angle`, so I'm not removing it even though not all applications support it.
